export const RESPONSE_VALIDATION = 'RESPONSE_VALIDATION';
export const RESPONSE_VALIDATION_VIEW = 'RESPONSE_VALIDATION_VIEW';
export const RESPONSE_VALIDATION_CREATE = 'RESPONSE_VALIDATION_CREATE';
export const RESPONSE_VALIDATION_UPDATE = 'RESPONSE_VALIDATION_UPDATE';
export const RESPONSE_VALIDATION_DELETE = 'RESPONSE_VALIDATION_DELETE';